# Generated by Django 4.2.10 on 2024-03-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudianti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Numero', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresidentClubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Numero', models.IntegerField()),
                ('Club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_enetcom.clubi')),
                ('etudi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_enetcom.etudianti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_membre', 'Can add les membres')],
            },
        ),
        migrations.CreateModel(
            name='MembreClubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_enetcom.clubi')),
                ('etud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_enetcom.etudianti')),
            ],
        ),
        migrations.AddField(
            model_name='clubi',
            name='membres',
            field=models.ManyToManyField(through='app_enetcom.MembreClubi', to='app_enetcom.etudianti'),
        ),
    ]
