# Generated by Django 5.0.2 on 2024-03-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enetcom', '0002_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='conversation_id',
        ),
        migrations.AlterField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app_enetcom.clubi'),
        ),
    ]
