# Generated by Django 5.0.2 on 2024-03-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enetcom', '0003_remove_messages_conversation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_enetcom.clubi')),
            ],
        ),
    ]
